env: flex
runtime: nodejs

# [START env]
env_variables:
  SQL_USER: root
  SQL_PASSWORD: root
  SQL_DATABASE: demo
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: node-gcp-189007:us-central1:demodb
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: node-gcp-189007:us-central1:demodb
# [END cloudsql_settings]